Auterion/px4-ros2-interface-lib

examples/cpp/modes/manual/include/mode.hpp
px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/include/px4_ros2/control/peripheral_actuators.hpp
px4_ros2_cpp/src/control/peripheral_actuators.cpp

To avoid any confusion with the Offboard interface.

rename OffboardActuatorControls to PeripheralActuatorControls

---

.github/workflows/build_and_test.yml

Fixes CI failures due to Empy version.
- See https://github.com/ros-tooling/setup-ros/pull/632

CI: Upgrade ros-tooling/setup-ros

---

examples/cpp/navigation/global_navigation/CMakeLists.txt
examples/cpp/navigation/local_navigation/CMakeLists.txt

Renames executables to reflect the naming used in the mode examples.
```
ros2 run example_global_navigation_cpp example_global_navigation_cpp
```
```
ros2 run example_global_navigation_cpp example_global_navigation
```
I'm updating the px4 user guide to reflect this change.

examples: rename navigation example executables

---

.github/workflows/build_and_test.yml
.github/workflows/lint.yml
examples/cpp/modes/goto/CMakeLists.txt
examples/cpp/modes/goto/include/mode.hpp
examples/cpp/modes/goto/include/util.hpp
examples/cpp/modes/goto/package.xml
examples/cpp/modes/goto/src/main.cpp
px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/include/px4_ros2/components/message_compatibility_check.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/goto.hpp
px4_ros2_cpp/src/control/setpoint_types/goto.cpp

Adds a "Go-to" setpoint type which streams a position and (optional) heading setpoint, meant to be handled by a position and heading smoother on the flight controller. Main idea: dump in whatever position and heading you want, and they will be smoothly followed by the autopilot. Additional fields for velocity and heading rate limits are included.
An example mode using the Go-to setpoint type is included:
https://github.com/Auterion/px4-ros2-interface-lib/assets/8026163/76795ebc-13b9-4637-b7f7-867e773047fa
Depends on: https://github.com/PX4/PX4-Autopilot/pull/22375
Docs: https://github.com/PX4/PX4-user_guide/pull/2935

Go-to setpoint type

---

px4_ros2_cpp/include/px4_ros2/odometry/global_position.hpp
px4_ros2_cpp/include/px4_ros2/odometry/local_position.hpp
px4_ros2_cpp/include/px4_ros2/odometry/subscription.hpp
px4_ros2_cpp/src/odometry/global_position.cpp
px4_ros2_cpp/src/odometry/local_position.cpp

Allows adding subscriptions to arbitrary ROS topics.
Users can register (multiple) callbacks or simply poll the last-received message.
```cpp
px4_ros2::Subscription<px4_msgs::msg::VehicleLocalPosition> ros_sub(context, "/fmu/out/vehicle_local_position");
// Create callback
ros_sub.onUpdate([](px4_msgs::msg::VehicleLocalPosition msg) {
std::cout << "Local pos from callback: " << msg.x << " " << msg.y << " " << msg.z << std::endl;
});
// Poll latest message
px4_msgs::msg::VehicleLocalPosition msg = ros_sub.last();
std::cout << "Local pos latest: " << msg.x << " " << msg.y << " " << msg.z << std::endl;
```

Generic subscriptions

---

examples/cpp/navigation/global_navigation/include/global_navigation.hpp
examples/cpp/navigation/local_navigation/include/local_navigation.hpp
px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/src/navigation/experimental/global_position_measurement_interface.cpp
px4_ros2_cpp/src/navigation/experimental/local_position_measurement_interface.cpp
px4_ros2_cpp/test/integration/arming_check.cpp
px4_ros2_cpp/test/integration/global_navigation.cpp
px4_ros2_cpp/test/integration/local_navigation.cpp
px4_ros2_cpp/test/integration/mode.cpp
px4_ros2_cpp/test/integration/mode_executor.cpp
px4_ros2_cpp/test/integration/overrides.cpp
px4_ros2_cpp/test/integration/util.hpp
px4_ros2_cpp/test/unit/global_navigation.cpp
px4_ros2_cpp/test/unit/local_navigation.cpp

- Publish invalid measurements and check exceptions are thrown correctly.
Test with `./build/px4_ros2_cpp/px4_ros2_cpp_unit_tests --gtest_filter='*Interface*'`
- Publish measurement via interface and check that PX4 confirms measurement fusion via estimator status flags.
- Log error message only once to avoid spamming the user when they catch interface exception.
- Add exception handling to examples
- Rename mode integration tests `Tester` -> `ModesTest`
**Jira**: [APX4-3591](https://auterion.atlassian.net/jira/software/c/projects/APX4/boards/225?selectedIssue=APX4-3591)
[APX4-3591]: https://auterion.atlassian.net/browse/APX4-3591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

tests: external navigation interface

---

px4_ros2_cpp/test/integration/local_navigation.cpp

Integration test was giving "Yaw unstable" warnings.
Pre-flight sim drone attitude points East not North, changed published attitude measurement accordingly.

tests: send correct drone attitude measurement

---

px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/attitude.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/rates.hpp
px4_ros2_cpp/include/px4_ros2/utils/frame_conversion.hpp
px4_ros2_cpp/include/px4_ros2/utils/geometry.hpp
px4_ros2_cpp/src/control/setpoint_types/experimental/attitude.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/rates.cpp
px4_ros2_cpp/test/unit/utils/frame_conversion.cpp
px4_ros2_cpp/test/unit/utils/geometry.cpp
px4_ros2_cpp/test/unit/utils/util.cpp
px4_ros2_cpp/test/unit/utils/util.hpp

- Utils for commonly used geometry/math
- Utils for commonly used ROS2 PX4 conversions (ENU/NED, FRD/FLU)
- templated methods
- `wrapAngleToPlusMinusPi` returns in [-pi, pi) instead of [-pi, pi] up to floating point precision
- rename `wrapAngleToPlusMinusPi` -> `wrapPi`
- Renamed `ned` to `frd` for thrust of attitude and rate setpoints
- Split auterion_sdk `utils.cpp` -> `{geometry.cpp, frame_conversion.cpp}`
- `quaternionToPitch` (and `...Roll`, `...Yaw`) functions. Rationale: existing`quaternionToEuler` maps pitch to [-pi/2, pi/2] by convention but there are use cases for a pitch in [-pi, pi] i.e. accumulating delta angles to detect a flip.
- Utils unit tests
- Utils doxygen docs

Add geometry and conversion utils

---

.clang-tidy
examples/cpp/modes/goto/include/mode.hpp
examples/cpp/modes/goto/include/util.hpp
examples/cpp/modes/manual/include/mode.hpp
examples/cpp/modes/mode_with_executor/include/mode.hpp
examples/cpp/modes/rtl_replacement/include/mode.hpp
examples/cpp/navigation/global_navigation/include/global_navigation.hpp
examples/cpp/navigation/local_navigation/include/local_navigation.hpp
px4_ros2_cpp/include/px4_ros2/common/setpoint_base.hpp
px4_ros2_cpp/include/px4_ros2/components/mode.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/direct_actuators.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/attitude.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/rates.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/goto.hpp
px4_ros2_cpp/src/components/message_compatibility_check.cpp
px4_ros2_cpp/src/components/mode.cpp
px4_ros2_cpp/src/components/mode_executor.cpp
px4_ros2_cpp/src/control/setpoint_types/goto.cpp
px4_ros2_cpp/test/integration/global_navigation.cpp
px4_ros2_cpp/test/integration/local_navigation.cpp
px4_ros2_cpp/test/integration/mode.cpp
px4_ros2_cpp/test/integration/mode_executor.cpp
px4_ros2_cpp/test/integration/overrides.cpp
px4_ros2_cpp/test/unit/global_navigation.cpp
px4_ros2_cpp/test/unit/local_navigation.cpp
px4_ros2_cpp/test/unit/utils/frame_conversion.cpp
px4_ros2_cpp/test/unit/utils/geometry.cpp

The original intent behind the check was only for L, as l is similar to 1.
https://clang.llvm.org/extra/clang-tidy/checks/readability/uppercase-literal-suffix.html
And some other clang-tidy changes:
- ignore very verbose misc-include-cleaner
- message_compatibility_check: move static methods to anonymous namespace

refactor: switch to lower-case float literal suffix (f) 

---

examples/cpp/modes/fw_attitude/CMakeLists.txt
examples/cpp/modes/fw_attitude/include/mode.hpp
examples/cpp/modes/fw_attitude/package.xml
examples/cpp/modes/fw_attitude/src/main.cpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/attitude.hpp
px4_ros2_cpp/include/px4_ros2/utils/geometry.hpp
px4_ros2_cpp/src/control/setpoint_types/experimental/attitude.cpp

Updated setpoint type attitude to update with euler angles instead of quaternions only.
Set small fixed attitude setpoint example for constant banking to show interface for FW

Add fw attitude example

---

px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/trajectory.hpp
px4_ros2_cpp/src/control/setpoint_types/experimental/trajectory.cpp

- `TrajectorySetpointType` additionally updates position, acceleration, yaw and yaw_rate

trajectory setpoint: finish update method

---

Doxyfile
examples/cpp/modes/fw_attitude/include/mode.hpp
examples/cpp/modes/fw_attitude/src/main.cpp
examples/cpp/modes/goto/include/mode.hpp
examples/cpp/modes/goto/src/main.cpp
examples/cpp/modes/goto_global/include/mode.hpp
examples/cpp/modes/goto_global/src/main.cpp
examples/cpp/modes/manual/include/mode.hpp
examples/cpp/modes/manual/src/main.cpp
examples/cpp/modes/mode_with_executor/include/mode.hpp
examples/cpp/modes/mode_with_executor/src/main.cpp
examples/cpp/modes/rtl_replacement/include/mode.hpp
examples/cpp/modes/rtl_replacement/src/main.cpp
px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/include/px4_ros2/components/node_with_mode.hpp
px4_ros2_cpp/include/px4_ros2/utils/frame_conversion.hpp
px4_ros2_cpp/include/px4_ros2/utils/geodesic.hpp
px4_ros2_cpp/include/px4_ros2/utils/geometry.hpp
px4_ros2_cpp/include/px4_ros2/utils/groups.dox
px4_ros2_cpp/src/utils/map_projection_impl.hpp
px4_ros2_cpp/test/unit/modes.cpp

- Adds template classes `NodeWithMode` and `NodeWithModeExecutor` to factorize repeated code in examples.
- `NodeWithMode<ModeT>` instantiates and registers a mode of type `ModeT`.
- `NodeWithModeExecutor<ExecutorModeT, ModeT>` instantiates and registers a mode executor of type `ExecutorModeT`. Also instantiates a mode of type `ModeT`, whose ownership is passed to the executor.
- Add doxygen group and subgroups for `utils/` folder.
- In Doxyfile, set `EXTRACT_STATIC = YES` because many utils functions are static qualified and weren't shown.
Example usage `NodeWithMode`:
```
class MyMode : public px4_ros2::ModeBase {...};
rclcpp::spin(std::make_shared<px4_ros2::NodeWithMode<MyMode>>("my_node"));
```
Example usage `NodeWithModeExecutor`: 
```
class MyMode : public px4_ros2::ModeBase {...}; …
```

components: add NodeWithMode class

---

examples/cpp/modes/goto/include/mode.hpp
examples/cpp/modes/goto_global/include/mode.hpp
px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/include/px4_ros2/components/message_compatibility_check.hpp
px4_ros2_cpp/include/px4_ros2/odometry/attitude.hpp
px4_ros2_cpp/include/px4_ros2/odometry/local_position.hpp
px4_ros2_cpp/src/odometry/attitude.cpp

- Add `OdometryAttitude` class.
- Add `heading()` getter to `OdometryLocalPosition` class.
- Use these interfaces in examples.
`OdometryAttitude::yaw()` and `OdometryLocalPosition::heading()` return the same value (up to PX4 timing), but I think it still makes sense to add a `OdometryLocalPosition::heading()` method for cases where the local position is already subscribed to e.g. in our local goto example.
**JIRA**: [APX4-3816](https://auterion.atlassian.net/browse/APX4-3816)
[APX4-3816]: https://auterion.atlassian.net/browse/APX4-3816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add OdometryAttitude class

---

.github/workflows/doxygen-gh-pages.yml
px4_ros2_cpp/include/px4_ros2/utils/geodesic.hpp

- Check doxygen script works on pull requests.
- Doxygen comment fixes that were causing the script to fail.

ci: check doxygen script works on PR and fix doxygen

---

px4_ros2_cpp/include/px4_ros2/common/requirement_flags.hpp
px4_ros2_cpp/include/px4_ros2/components/manual_control_input.hpp
px4_ros2_cpp/include/px4_ros2/components/mode.hpp
px4_ros2_cpp/include/px4_ros2/components/mode_executor.hpp
px4_ros2_cpp/include/px4_ros2/control/peripheral_actuators.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/direct_actuators.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/attitude.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/rates.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/trajectory.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/goto.hpp
px4_ros2_cpp/include/px4_ros2/navigation/experimental/navigation_interface_base.hpp
px4_ros2_cpp/include/px4_ros2/odometry/attitude.hpp
px4_ros2_cpp/include/px4_ros2/odometry/global_position.hpp
px4_ros2_cpp/include/px4_ros2/odometry/local_position.hpp
px4_ros2_cpp/include/px4_ros2/odometry/subscription.hpp

As mentioned [here](https://github.com/PX4/PX4-user_guide/pull/3076#pullrequestreview-1904929489), some doxygen annotations are missing from the "Class view" tab.
This adds the existing docs to the high level overview, and some extra descriptions.
Before:
After:

doxygen: add high level docs for classes

---

px4_ros2_cpp/include/px4_ros2/control/setpoint_types/direct_actuators.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/attitude.hpp
px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/rates.hpp
px4_ros2_cpp/src/components/mode.cpp

- Reduce default control update frequency to 100Hz
- Do not trigger `setSetpointUpdateRateFromSetpointTypes()` after registration if the mode has already set a desired setpoint update rate (e.g. already called `setSetpointUpdateRate()` in the mode constructor)
- Tested in SITL that the expected control frequency is set when specifying / not specifying an update rate in the mode's constructor / onActivate

control: reduce default control update frequency

---

.vscode/settings.json
README.md
examples/cpp/modes/rtl_replacement/include/mode.hpp
px4_ros2_cpp/include/px4_ros2/components/message_compatibility_check.hpp
px4_ros2_cpp/src/components/health_and_arming_checks.cpp
px4_ros2_cpp/src/components/manual_control_input.cpp
px4_ros2_cpp/src/components/message_compatibility_check.cpp
px4_ros2_cpp/src/components/mode.cpp
px4_ros2_cpp/src/components/mode_executor.cpp
px4_ros2_cpp/src/components/overrides.cpp
px4_ros2_cpp/src/components/registration.cpp
px4_ros2_cpp/src/components/wait_for_fmu.cpp
px4_ros2_cpp/src/control/peripheral_actuators.cpp
px4_ros2_cpp/src/control/setpoint_types/direct_actuators.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/attitude.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/rates.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/trajectory.cpp
px4_ros2_cpp/src/control/setpoint_types/goto.cpp
px4_ros2_cpp/src/navigation/experimental/global_position_measurement_interface.cpp
px4_ros2_cpp/src/navigation/experimental/local_position_measurement_interface.cpp
px4_ros2_cpp/src/odometry/attitude.cpp
px4_ros2_cpp/src/odometry/global_position.cpp
px4_ros2_cpp/src/odometry/local_position.cpp
px4_ros2_cpp/src/utils/geodesic.cpp
px4_ros2_cpp/test/integration/global_navigation.cpp
px4_ros2_cpp/test/integration/local_navigation.cpp
px4_ros2_cpp/test/integration/util.cpp
scripts/check-used-topics.py

Currently the library do not take into account the namespace if specified. The micro DDS client allows in PX4 to configure a custom namespace (multiple drones on the same network). To reflect this, it would be good to also allow this library to use custom namespaces. Removing "/" in front of topic definitions solve this. The topics will reflect the chosen namespace for the node.

fix usage of ROS namespaces

---

px4_ros2_cpp/include/px4_ros2/components/mode_executor.hpp
px4_ros2_cpp/src/components/mode_executor.cpp
px4_ros2_cpp/test/integration/mode_executor.cpp
px4_ros2_cpp/test/integration/overrides.cpp

feat: new setting to allow arming with executor

---

README.md
scripts/check-message-compatibility.py
scripts/check-used-topics.py

Adds a script to compare the message definition sets of two repos
To determine if the px4-ros2 library is compatible with a specific version of `PX4` when it depends on a particular version of `px4_msgs`:
```
$ ./scripts/check-message-compatibility.py ../px4_msgs/ ../APX4/
``` 
```
$ ./scripts/check-message-compatibility.py -v ../px4_msgs/ ../APX4/
Checking the following message files:
- ActuatorMotors.msg
- ActuatorServos.msg
- ArmingCheckReply.msg
- ArmingCheckRequest.msg
- ConfigOverrides.msg
- GotoSetpoint.msg
- ManualControlSetpoint.msg
- ModeCompleted.msg
- RegisterExtComponentReply.msg
- RegisterExtComponentRequest.msg
- TrajectorySetpoint.msg
- UnregisterExtComponent.msg
- VehicleAngularVelocity.msg
- VehicleAttitude.msg
- VehicleAttitudeSetpoint.msg
- VehicleCommand.msg
- …
```

scripts: add script to compare message sets

---

scripts/check-message-compatibility.py

It does not support the typing classes.
Python 3.8 is almost EOL.

check-message-compatibility: add python 3.8 support

---

px4_ros2_cpp/include/px4_ros2/navigation/experimental/global_position_measurement_interface.hpp
px4_ros2_cpp/src/navigation/experimental/global_position_measurement_interface.cpp
px4_ros2_cpp/test/unit/global_navigation.cpp

Add reset method to increment the position reset counter
Only incrementing the lat_lon reset counter since it seems to be the only counter processed in the AuxGlobalPosition module in PX4: https://github.com/Auterion/PX4_firmware_private/blob/eaa169d211a19ecbd37a454846eb117e40ec204d/src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.cpp#L59
Only unit-testing

Add global navigation reset method

---

px4_ros2_cpp/include/px4_ros2/components/mode.hpp

Enhanced mode replacement options to consider Loiter, nav-state 4.
Testing

mode: extends available replacements to loiter mode

---

.github/workflows/lint.yml

The `ubuntu-latest` GitHub Actions runner upgraded from Ubuntu 22.04 to 24.04 in December 2024.
`ament-lint` is not yet available on Ubuntu 24.04, so here we pin the runner to `ubuntu-22.04`.

Run linting CI on Ubuntu 22.04

---

px4_ros2_cpp/src/components/health_and_arming_checks.cpp
px4_ros2_cpp/src/components/message_compatibility_check.cpp
px4_ros2_cpp/src/components/mode.cpp
px4_ros2_cpp/src/components/mode_executor.cpp
px4_ros2_cpp/src/components/overrides.cpp
px4_ros2_cpp/src/components/registration.cpp
px4_ros2_cpp/src/control/peripheral_actuators.cpp
px4_ros2_cpp/src/control/setpoint_types/direct_actuators.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/attitude.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/rates.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/trajectory.cpp
px4_ros2_cpp/src/control/setpoint_types/goto.cpp
px4_ros2_cpp/src/navigation/experimental/global_position_measurement_interface.cpp
px4_ros2_cpp/src/navigation/experimental/local_position_measurement_interface.cpp
px4_ros2_cpp/test/integration/util.cpp

Instead let PX4 set the local timestamp when receiving the data. In most cases the timestamp is only relevant for logging, or checked that it is not too old.
This is to avoid relying on timesync, as we experienced a number of issues:
- we had cases where on real setups, the time was off by more than 500ms, leading to rejected goto_setpoint samples.
- when using AirSim SITL, there's generally a time mismatch. This was not closer investigated yet.
- there's often warnings from timesync

do not set timestamp for publications

---

px4_ros2_cpp/include/px4_ros2/components/mode_executor.hpp
px4_ros2_cpp/src/components/mode_executor.cpp

The behavior between ROS Humble and Jazzy differs: Jazzy now throws an exception 'subscription already associated with a wait set'. Apparently because the subscription is already in the node executor. This works around that by creating the subscription right before use.
This also adds retries when a command/ack times out.
Tested on Jazzy and Humble.

fix mode_executor under ROS Jazzy: create vehicle command ack subscription right before use

---

scripts/check-message-compatibility.py

Currently, the script always failed because it can't find the files inside the versioned message folder, with this commit, I'm searching all the subfolders in the `msg` directory, to find the files. Thereby, messages in the versioned folder are also found.
An open issue is that the `px4_msgs` are not up-to-date with the version field in the message definition, and thereby the check fails.
There, the question would be if that field will also be present in the px4_msgs repo, or should we just exclude this in the compensation? @bkueng

updated the script to consider versioned paths

---

px4_ros2_cpp/src/control/setpoint_types/fixedwing/fw_control_setpoint.cpp

Following commit in fw-ctrl-api branch in px4:  https://github.com/PX4/PX4-Autopilot/pull/24056/commits/55be9648e8438eb1e6ca1387fab6276313751f80
Removed check that all control limits need to be set for publishing.

fw-ctrl: allow setting any subset of control limits.

---

px4_ros2_cpp/include/px4_ros2/control/setpoint_types/experimental/trajectory.hpp
px4_ros2_cpp/src/control/setpoint_types/experimental/trajectory.cpp

Hey @bkueng I made an attempt at implementing what we discussed in #78 
This makes the TrajectorySetpointType more flexible by allowing the user to set position, velocity, acceleration, yaw, and yaw rate individually. For this we introduce a new helper struct TrajectorySetpoint with a builder pattern to set the different values.
I might have overdone it by making all fields individually settable through the builder pattern but I thought it would be more convenient than having to mix field access and builder pattern.
We tested this really quickly in simulation and it seems to work.
Let me know if you want me to change anything.

Make TrajectorySetpointType more flexible

---

px4_ros2_cpp/include/px4_ros2/odometry/global_position.hpp
px4_ros2_cpp/test/integration/global_navigation.cpp

Fixes integration test that was sending out hardcoded global positioning, causing the EKF to reject the injected position.
Tested with https://github.com/PX4/PX4-Autopilot/pull/24658

fix: global position interface test

---

px4_ros2_cpp/rosdep-foxy.yaml
px4_ros2_cpp/rosdep-humble.yaml
px4_ros2_cpp/rosdep-rolling.yaml

For release workflows which use rosdep to install dependencies, pin the version of the Auterion PX4 messages package.

build: pin auterion px4 messages version during releases

---

px4_ros2_cpp/include/px4_ros2/components/mode_executor.hpp
px4_ros2_cpp/src/components/health_and_arming_checks.cpp
px4_ros2_cpp/src/components/manual_control_input.cpp
px4_ros2_cpp/src/components/message_compatibility_check.cpp
px4_ros2_cpp/src/components/mode.cpp
px4_ros2_cpp/src/components/mode_executor.cpp
px4_ros2_cpp/src/components/overrides.cpp
px4_ros2_cpp/src/components/registration.cpp
px4_ros2_cpp/src/components/wait_for_fmu.cpp
px4_ros2_cpp/src/control/peripheral_actuators.cpp
px4_ros2_cpp/src/control/setpoint_types/direct_actuators.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/attitude.cpp
px4_ros2_cpp/src/control/setpoint_types/experimental/rates.cpp
px4_ros2_cpp/src/control/setpoint_types/goto.cpp
px4_ros2_cpp/src/navigation/experimental/global_position_measurement_interface.cpp
px4_ros2_cpp/src/navigation/experimental/local_position_measurement_interface.cpp
px4_ros2_cpp/src/utils/geodesic.cpp
px4_ros2_cpp/test/integration/global_navigation.cpp
px4_ros2_cpp/test/integration/local_navigation.cpp
px4_ros2_cpp/test/integration/mode_executor.cpp
px4_ros2_cpp/test/integration/overrides.cpp
px4_ros2_cpp/test/integration/util.cpp
px4_ros2_cpp/test/unit/global_navigation.cpp

This PR introduces the disarm function to the mode executor. it is also possible to force the disarm. This is highly linked to this [PR](https://github.com/Auterion/px4-ros2-interface-lib/pull/99) and the use case is the same

Added possibility to disarm the drone from a mode executor

---

.github/workflows/build_and_test.yml
.github/workflows/doxygen-gh-pages.yml
.github/workflows/lint.yml

Right now the CI has the following warning messages:
```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```
This removes some of the warning messages by using `apt-get` instead of `apt` to make the CI logs cleaner to read.

Replace apt with apt-get to reduce warnings in the CI logs

---

examples/cpp/modes/executor_with_multiple_modes/CMakeLists.txt
examples/cpp/modes/fw_attitude/CMakeLists.txt
examples/cpp/modes/goto/CMakeLists.txt
examples/cpp/modes/goto_global/CMakeLists.txt
examples/cpp/modes/manual/CMakeLists.txt
examples/cpp/modes/mode_with_executor/CMakeLists.txt
examples/cpp/modes/rtl_replacement/CMakeLists.txt
examples/cpp/navigation/global_navigation/CMakeLists.txt
examples/cpp/navigation/local_navigation/CMakeLists.txt
px4_ros2_cpp/CMakeLists.txt

ROS 2 is deprecating `ament_target_dependencies` with a preference to switch to `target_link_libraries`. This updates the CMakeLists to use `target_link_libraries`. Everything builds correctly.

Remove deprecated ament_target_dependencies

---

px4_ros2_cpp/include/px4_ros2/control/vtol.hpp
px4_ros2_cpp/src/control/vtol.cpp

Add function to compute acceleration setpoint during a vtol transition.   `TrajectorySetpoint.msg` sets: 
- `acceleration = {0.f, 0.f, NAN}` during front transition and decelerates during back transition

[against another PR] VTOL Transition acceleration setpoint computation 

---

px4_ros2_cpp/include/px4_ros2/control/setpoint_types/fixedwing_lateral_longitudinal.hpp

See commit. 
Small typo in docs

fixedwing_lateral_longitudinal: fix typo in docs

---

px4_ros2_cpp/src/control/vtol.cpp

Sporadically with SDK commanded backtransitions, it applied maximum pitch / deceleration, even though the deceleration setpoint given to the `auterion::vtol::TransitionSetpoint` is always smooth and below 2 m/s^2. After some print debugging (*) I found that the deceleration used here is sometimes NaN in the first couple samples. This means that the pitch setpoint _stays_ NaN (until reset to 0 in the next backtransition), and the NaN makes its way to the acceleration given to PX4 via trajectory setpoint. 
The proposed fix continues applying the existing pitch setpoint in that case. If NaN decelerations occur at the start of the backtransition, we delay the deceleration until we have valid deceleration measurements. 
Is the case of sustained NaN values possible / likely enough to warrant …

VTOL: robustify against NaN deceleration

---

px4_ros2_cpp/include/px4_ros2/mission/mission_executor.hpp

This PR adds the failsafe deferral interface of the mission executor to the action handler. It is needed to enable or disable the failsafe deferral from a mission action.

Add interface for failsafe deferral to ActionHandler

---

px4_ros2_cpp/include/px4_ros2/utils/geometry.hpp

This PR allows to switch to ZYX conversion when converting quaternion to euler angles. There are no issues with the current conversion when the drone is in normal flying conditions (non tilted). However the computation diverges completely from reality when the drone is upside down. 
A good angle computation when upside down is particularly useful in specific modes such a turtle mode (ability to flip the drone when this is upside down) therefore I propose to switch to the ZYX computation as proposed in this PR

Use ZYX sequence for quaternion to euler angle conversion

---

.github/workflows/build_and_test.yml
.github/workflows/doxygen-gh-pages.yml

Update the CI to use self-hosted runners

Switch to self-hosted runners

---

px4_ros2_cpp/include/px4_ros2/utils/message_version.hpp

Doxygen was giving the error:
```
/home/guillaume/repos/px4-ros2-interface-lib/px4_ros2_cpp/include/px4_ros2/utils/message_version.hpp:23: warning: explicit link request to 'value' could not be resolved
```
This prevents doxygen from the trying to link the `value` symbol and instead just presents it as inline code.

fix: unresolved link to "value"

---

scripts/check-message-compatibility.py

The `check-message-compatibility.py` script does not handle cases where one of the messages to check is missing from either input repository:
```
File "/home/guillaume/repos/px4-ros2-interface-lib/./scripts/check-message-compatibility.py", line 24, in message_fields_str_for_message_hash
with open(filename, 'r') as file:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
This adds handling of the missing message case, which the script will also flag as an incompatibility. Now the output may looks something like:
```
$ ./scripts/check-message-compatibility.py ../PX4/ ../px4_msgs
Error: Message definition file ActuatorServos.msg not found in ../PX4/
Error: Message definition file VehicleGlobalPosition.msg not found in ../px4_msgs
FAILED! Some files differ:
- …
```

fix(scripts): message compat script should handle missing messages

---

examples/cpp/modes/executor_with_multiple_modes/include/executor.hpp
examples/cpp/modes/mode_with_executor/include/mode.hpp
px4_ros2_cpp/include/px4_ros2/components/mode_executor.hpp
px4_ros2_cpp/include/px4_ros2/components/node_with_mode.hpp
px4_ros2_cpp/include/px4_ros2/mission/mission_executor.hpp
px4_ros2_cpp/src/components/mode_executor.cpp
px4_ros2_cpp/test/integration/mode_executor.cpp
px4_ros2_cpp/test/integration/overrides.cpp

These can be accessed from the mode and need to be the same anyway

mode_executor: remove node and topic namespace prefix constructor args

---

px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/include/px4_ros2/components/message_compatibility_check.hpp
px4_ros2_cpp/include/px4_ros2/utils/message_version.hpp
px4_ros2_cpp/src/components/message_compatibility_check.cpp
px4_ros2_cpp/src/components/px4_all_messages.hpp.em

When using PX4 with rmw_zenoh_cpp with PX4/PX4-Autopilot#24476
We use RIHS01 hashes instead to check type support
This patch fixes that so that px4-ros2-interface-lib works with rmw_zenoh_cpp

Add rmw_zenoh_cpp support by using RIHS01 hashes

---

.github/workflows/px4_build.yml
px4_ros2_cpp/CMakeLists.txt
px4_ros2_cpp/src/components/message_compatibility_check.cpp

To ensure the corresponding PX4-Autopilot CI does not break.

ci: add build in px4 dev container
